### ISSUE TITLE
Setting/Getting Document attributes

### ISSUE THREAD

**Issue by Bashirkazimi** [jina-ai/executor-image-torch-encoder#34]
Hi,

In the example below:

```
import numpy as np

from jina import Flow, Document

f = Flow().add(uses='jinahub+docker://ImageTorchEncoder')

doc = Document(blob=np.ones((224, 224, 3), dtype=np.uint8))

with f:
    f.post(on='/index', inputs=doc, on_done=lambda resp: print(resp.docs[0].embedding))
```

You are printing the `resp.docs[0].embedding`. I tried to see where this has been set in the code, I could not find it.

The only place where an attribute of the Document is set/altered is in the [ImageTorchEncoder](https://github.com/jina-ai/executor-image-torch-encoder/blob/main/executor/torch_encoder.py) file in line `110`:

`document_batch.embeddings = features`

Could you please give a hint of how it works? The attribute in the line above is `embeddings` and not `embedding`. 

I thought it might understand plural/singular automatically. So I tried to change `document_batch.embeddings = features` to `document_batch.embs = features` and tried to print:
```
with f:
    f.post(on='/index', inputs=doc, on_done=lambda resp: print(resp.docs[0].emb))
```

but it does not work like that.

Thank you in advance for writing back :)

**Comment by JoanFM** [comment]
Hello @Bashirkazimi,

The plural/singular problem comes from the assigning of the embedding of a single Document vs the assignment to a batch of Documents.

You can learn more about this syntax in docarray.jina.ai.

Please notice that this repo is right now not up to date to latest version but will be adapted soon

**Comment by nan-wang** [comment]
@Bashirkazimi Here is the documentation about the usage of `.embeddings`. It is a sugary attribute for simplicity. 
https://docarray.jina.ai/fundamentals/documentarray/access-attributes/#content-and-embedding-sugary-attributes

**Comment by Bashirkazimi** [comment]
@nan-wang @JoanFM Thanks for replying :)
